### PR TITLE
Remove mirror workflow and state branch policy

### PR DESCRIPTION
**Pull request by emersonknapp**
See comment https://github.com/ros-visualization/rqt_bag/commit/5048c25ffc0baeb5658b6986298ab4c7ecb4808a#r90157284 for more context

* TODO:
  *  Mark "Lock Branch" option for `ros2` branch, so that it can't be written to at all - this should block further PRs and remove that confusion

### CODE REVIEW

**Comment by clalancette** [comment]
See my response in https://github.com/ros-visualization/rqt_bag/pull/126#issuecomment-1317863624 .  I'm not convinced that this is what we should do.

**Comment by emersonknapp** [comment]
I've updated the description to my newest proposal - I haven't seen from what you've said why the branch mirroring should exist.

**Review by mjeronimo — APPROVED** [review]

**Review by audrow — APPROVED** [review]
I'm okay with this if we think it is the best thing to do.

**Comment by mjeronimo** [comment]
@clalancette Are you OK with this one?

**Comment by clalancette** [comment]
> @clalancette Are you OK with this one?

Yeah, that's fine.  Let's go ahead.

**Pull request merged**
