### PR TITLE
Update the package.xml files with the latest Open Robotics maintainers

### PR DESCRIPTION
**Pull request by mjeronimo**
See title :) 

Signed-off-by: Michael Jeronimo <michael.jeronimo@openrobotics.org>

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I think it is safe to assume that neither Aaron nor Austin are actually maintaining the packages in this repository.

Please remove both as well as me as maintainer but add all three as authors.

**Comment by dirk-thomas** [comment]
Please use the order of tags as defined in the schema: https://github.com/ros-infrastructure/rep/blob/3486e2328c83e115191e7de4335e22c721daccf9/xsd/package_format3.xsd#L86-L90

**Comment by mjeronimo** [comment]
@dirk-thomas  Would you prefer <author>s with or without e-mail addresses?

**Comment by dirk-thomas** [comment]
>  Would you prefer <author>s with or without e-mail addresses?

I don't mind either way.

>  Also, stylistically, are we blocking sections or removing blank lines?

We don't have a consistent style I think. I usually try to make sure that the different dependency types are blocks but all the other metainfo can be without empty line (or keep them as is).

**Review by dirk-thomas — APPROVED** [review]

**Pull request merged**
