### PR TITLE
Fix crash during merge sort of bag entries (fixes #90)

### LINKED ISSUE #90: Timeline not displayed due to no '_mergesort' function
It seems the `_mergesort` function in the `rosbag.bag` was replaced by `heapq.merge` (https://github.com/ros/ros_comm/pull/2017).
But in the current version https://github.com/ros-visualization/rqt_bag/blob/b36db71b0af957853a113b9336f5929a5c4d7fc3/rqt_bag/src/rqt_bag/bag_timeline.py#L273
and
https://github.com/ros-visualization/rqt_bag/blob/b36db71b0af957853a113b9336f5929a5c4d7fc3/rqt_bag/src/rqt_bag/bag_timeline.py#L303
the old function was still called.
This might cause the timeline to show incorrectly.

### PR DESCRIPTION
**Pull request by MichaelGrupp**
As noted in #90, the previously used function was [removed](https://github.com/ros/ros_comm/pull/2017) in ros_comm
for Noetic.

This makes rqt_bag usable again on ROS Noetic and is compatible with
Python 2 distros.

### CODE REVIEW

**Comment by peterpedron** [comment]
This is very useful. Please merge asap!

**Review by peterpedron — APPROVED** [review]

**Comment by peci1** [comment]
I can confirm this doesn't break Melodic :)

**Comment by MichaelGrupp** [comment]
@mjeronimo or @mabelzhang, can you please take a look?

**Comment by wxmerkt** [comment]
Thank you! :-) Could we get a patch-release with this fix please?

**Comment by peci1** [comment]
I'd suggest releasing after #94 is merged, too...

**Comment by mjeronimo** [comment]
Yes, I can release ASAP with both #93 and #94. Thanks for the fixes.

**Review by mjeronimo — COMMENTED** [review]
LGTM.

**Comment by tkazik** [comment]
Thx for the fix! :+1: 
Would it make sense to also replace `_mergesort` [here](https://github.com/magazino/rqt_bag/blob/3a5a1361e3ffbe51523426ee0dc4d46fd6f63d3f/rqt_bag/src/rqt_bag/bag_timeline.py#L287)? It is just a few lines below and using the same function would be a bit more consistent. (Actually I think that someone eventually would run into a bug, if the function `get_entries_with_bags()` would be called.)
What do you think?

**Comment by MichaelGrupp** [comment]
@tkazik Yes, the save functionality is also broken. I created #96 as a patch.

**Pull request merged**
