### PR TITLE
Fix raw view

### LINKED ISSUE #92: Rqt_bag crashed for "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)"
Help, after I upgraded to the latest rqt_bag, it will crash view raw topic which contains ASCII code such as Chinese character 中文

```log
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_bag/plugins/message_view.py", line 93, in event
    self.message_viewed(bag, msg_data)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_bag/plugins/raw_view.py", line 73, in message_viewed
    self.message_tree.set_message(msg)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_bag/plugins/raw_view.py", line 115, in set_message
    self._add_msg_object(None, '', '', msg, msg._type)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_bag/plugins/raw_view.py", line 239, in _add_msg_object
    self._add_msg_object(item, subpath, subobj_name, subobj, subobj_type)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_bag/plugins/raw_view.py", line 207, in _add_msg_object
    obj_repr = codecs.utf_8_decode(str(obj).encode(), 'ignore')[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
[1]    16885 abort (core dumped)  rqt_bag data_big_2020-12-31-06-54-03_0.bag
```

### PR DESCRIPTION
**Pull request by peci1**
Fixes #92. Partly reverts #68.

I never know with the encode/decode things, but this is what fixed raw view for me.

### CODE REVIEW

**Comment by peci1** [comment]
@mjeronimo do you remember why you touched raw view in an image_view PR?

**Comment by peci1** [comment]
Maybe I should add that this is a fix for Melodic. Not tested on Noetic. Could that be the reason why the encode was added?

**Comment by mjeronimo** [comment]
@peci1 Yes, please test on Kinetic and Noetic as well, if you would. If I recall the code did need to be slightly different for each.

**Comment by peci1** [comment]
So, Noetic doesn't need this PR. I'll test on Kinetic later.

**Comment by peci1** [comment]
Kinetic requires this PR.

**Comment by peci1** [comment]
I updated this PR with a version that works on Kinetic, Melodic and Noetic.

**Review by mjeronimo — APPROVED** [review]

**Comment by peci1** [comment]
Thanks ;)

**Pull request merged**
