### PR TITLE
Highlight topic being selected when opening right-click panel

### PR DESCRIPTION
**Pull request by ivanpauno**
Depends on https://github.com/ros-visualization/rqt_bag/pull/114.

This is how it looks, maybe there's a better way to highlight it

image

### CODE REVIEW

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16933/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11497/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17330/)

**Review by wjwwood — APPROVED** [review]
I don't know how hard it would be but if you could instead highlight the while horizontal row you've selected that would be better. Also typically selection is a very light blue (or sometimes affected but he system color scheme) highlight. 

But this is definitely an incremental improvement.

**Comment by wjwwood** [comment]
Also the dark green highlight makes the text hard to read so maybe a lighter color to highlight or switch the text to white as well as highlight.

**Comment by ivanpauno** [comment]
I have integrated these changes in https://github.com/ros-visualization/rqt_bag/pull/116, to avoid creating code conflicts.
That PR is still pretty small.

---

> I don't know how hard it would be but if you could instead highlight the while horizontal row you've selected that would be better.

Addressed.
I didn't highlight the timeline, because that will probably look weird, but the highlighting is more notorious now.

>Also typically selection is a very light blue (or sometimes affected but he system color scheme) highlight.

Addressed.

> Also the dark green highlight makes the text hard to read so maybe a lighter color to highlight or switch the text to white as well as highlight.

Addressed.

**Pull request closed without merging**
