### PR TITLE
ensure data types match what PyQt expects

### PR DESCRIPTION
**Pull request by ijnek**
Some more fixes for #111

### CODE REVIEW

**Comment by ijnek** [comment]
Pinging this @ivanpauno, would you be able to review please? #111 explains why these changes are necessary.

**Review by ivanpauno — APPROVED** [review]
LGTM!

I will do some testing locally before merging

**Comment by ivanpauno** [comment]
@ijnek I needed one extra change to make rqt_bag work, could you double check it?

**Comment by ijnek** [comment]
@ivanpauno LGTM

**Comment by ivanpauno** [comment]
I forgot to run CI ...
There shouldn't be surprises but just in case:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17162/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11706/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17585/)

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/when-will-rqt-bag-be-synced-on-humble/27168/4

**Comment by ivanpauno** [comment]
@mergifyio backport humble

**Comment by ahcorde** [comment]
Pulls: ros-visualization/rqt_bag#118
Gist: https://gist.githubusercontent.com/ahcorde/314192a0e87f71f1efcc1e1d528d24df/raw/e839bc53512d3bbb2d00b02ab7fa1d957e8b98e9/ros2.repos
BUILD args:  --packages-above-and-dependencies rqt_bag
TEST args:  --packages-above rqt_bag
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/19539
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/29388/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/22172/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/9279/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/28335/)

**Pull request merged**
