### PR TITLE
Adapted to rosbag2_py

### PR DESCRIPTION
**Pull request by ahcorde**
This PR fix the new changes included in rosbag2_py. 

Still a draft.

Requires https://github.com/ros2/rosbag2/pull/1642

# TODO

 - interface is almost freeze while recording

### CODE REVIEW

**Comment by ahcorde** [comment]
# TODO 
When I read a bag file and try to click on the checkboxes, I'm only able to publish the second element of the list if there are more than 1 element.

**Comment by clalancette** [comment]
I just updated the license for the code we are adapting from PIL.

Besides that, I did a quick test with this.  I ran a demo (`ros2 run demo_nodes_cpp talker`), recorded a bag (`ros2 bag record /chatter`), and then opened the bag with rqt_bag.  As soon as I opened the bag, the CPU usage of the `rqt` process spiked to 100% and stayed there.  I am going to poke at that next.

**Review by clalancette — APPROVED** [review]
This is a definite improvement; at least basic things work now.  We still need to deal with QoSProfiles as they come from the bag, and while testing I noticed that trying to open another bag on top of the first one doesn't work.  But that is all fixes for another day.

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21070/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15374/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21786/)

**Comment by clalancette** [comment]
@mergifyio backport jazzy

**Pull request merged**
