### PR TITLE
Updated player QoS

### PR DESCRIPTION
**Pull request by ahcorde**
Related to this PR in rosbag2_py which allow to instrospect QoS of rosbag topics https://github.com/ros2/rosbag2/pull/1648

The PR on rosbag is on hold because of this comment https://github.com/ros2/rosbag2/pull/1648#discussion_r1596893671

### CODE REVIEW

**Comment by ahcorde** [comment]
@clalancette required PR is merged on rosbag2. This PR is ready

**Review by mjcarroll — APPROVED** [review]
LGTM with CI

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21714/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15991/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1221/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22419/)

**Review by clalancette — APPROVED** [review]

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport jazzy

**Pull request merged**
